// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppLog10
SEXP cppLog10(SEXP quasarclPtr_, SEXP inputMatrix_);
RcppExport SEXP quasar_cppLog10(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppLog10(quasarclPtr_, inputMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppMinusMatrix
SEXP cppMinusMatrix(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP subtrahendMatrix_);
RcppExport SEXP quasar_cppMinusMatrix(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP subtrahendMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type subtrahendMatrix_(subtrahendMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppMinusMatrix(quasarclPtr_, inputMatrix_, subtrahendMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppMinusScalar
SEXP cppMinusScalar(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP scalar_);
RcppExport SEXP quasar_cppMinusScalar(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP scalar_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type scalar_(scalar_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppMinusScalar(quasarclPtr_, inputMatrix_, scalar_));
    return rcpp_result_gen;
END_RCPP
}
// cppMultiplyCol
SEXP cppMultiplyCol(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP vector_);
RcppExport SEXP quasar_cppMultiplyCol(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP vector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type vector_(vector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppMultiplyCol(quasarclPtr_, inputMatrix_, vector_));
    return rcpp_result_gen;
END_RCPP
}
// cppTranspose
SEXP cppTranspose(SEXP quasarclPtr_, SEXP inputMatrix_);
RcppExport SEXP quasar_cppTranspose(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppTranspose(quasarclPtr_, inputMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppDivide
SEXP cppDivide(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP divisorMatrix_);
RcppExport SEXP quasar_cppDivide(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP divisorMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type divisorMatrix_(divisorMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppDivide(quasarclPtr_, inputMatrix_, divisorMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppFixReglinResults
SEXP cppFixReglinResults(SEXP quasarclPtr_, SEXP cReglinResultsVector_, SEXP reglinResultsVector_);
RcppExport SEXP quasar_cppFixReglinResults(SEXP quasarclPtr_SEXP, SEXP cReglinResultsVector_SEXP, SEXP reglinResultsVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type cReglinResultsVector_(cReglinResultsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type reglinResultsVector_(reglinResultsVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFixReglinResults(quasarclPtr_, cReglinResultsVector_, reglinResultsVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcCfunDcfun
SEXP cppCalcCfunDcfun(SEXP quasarclPtr_, SEXP wavelengthsMatrix_, SEXP dcontinuumsMatrix_, SEXP continuumsMatrix_, SEXP cReglinResultsVector_, SEXP reglinResultsVector_);
RcppExport SEXP quasar_cppCalcCfunDcfun(SEXP quasarclPtr_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP dcontinuumsMatrix_SEXP, SEXP continuumsMatrix_SEXP, SEXP cReglinResultsVector_SEXP, SEXP reglinResultsVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dcontinuumsMatrix_(dcontinuumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type continuumsMatrix_(continuumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type cReglinResultsVector_(cReglinResultsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type reglinResultsVector_(reglinResultsVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcCfunDcfun(quasarclPtr_, wavelengthsMatrix_, dcontinuumsMatrix_, continuumsMatrix_, cReglinResultsVector_, reglinResultsVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcCw
SEXP cppCalcCw(SEXP quasarclPtr_, SEXP wavelengthsMatrix_, SEXP continuumsMatrix_, SEXP cReglinResultsVector_);
RcppExport SEXP quasar_cppCalcCw(SEXP quasarclPtr_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP continuumsMatrix_SEXP, SEXP cReglinResultsVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type continuumsMatrix_(continuumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type cReglinResultsVector_(cReglinResultsVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcCw(quasarclPtr_, wavelengthsMatrix_, continuumsMatrix_, cReglinResultsVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppReduceContinuumChisqs
SEXP cppReduceContinuumChisqs(SEXP quasarclPtr_, SEXP chisqsVector_, SEXP sizesVector_);
RcppExport SEXP quasar_cppReduceContinuumChisqs(SEXP quasarclPtr_SEXP, SEXP chisqsVector_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type chisqsVector_(chisqsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppReduceContinuumChisqs(quasarclPtr_, chisqsVector_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppContinuum
SEXP cppContinuum(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP wavelengthsMatrix_, SEXP errorsMatrix_, SEXP sizesVector_, SEXP windowsVector_, SEXP ampWavelength_);
RcppExport SEXP quasar_cppContinuum(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP windowsVector_SEXP, SEXP ampWavelength_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type windowsVector_(windowsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ampWavelength_(ampWavelength_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppContinuum(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_, ampWavelength_));
    return rcpp_result_gen;
END_RCPP
}
// cppFeFit
SEXP cppFeFit(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP wavelengthsMatrix_, SEXP errorsMatrix_, SEXP continuumsMatrix_, SEXP sizesVector_, SEXP feTemplateList_, SEXP windowsVector_, SEXP fitParametersList_);
RcppExport SEXP quasar_cppFeFit(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP continuumsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP feTemplateList_SEXP, SEXP windowsVector_SEXP, SEXP fitParametersList_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type continuumsMatrix_(continuumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type feTemplateList_(feTemplateList_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type windowsVector_(windowsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitParametersList_(fitParametersList_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFeFit(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, continuumsMatrix_, sizesVector_, feTemplateList_, windowsVector_, fitParametersList_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcFeTemplateMatrix
SEXP cppCalcFeTemplateMatrix(SEXP quasarclPtr_, SEXP wavelengthsMatrix_, SEXP sizesVector_, SEXP feTemplateList_, SEXP fitParametersList_);
RcppExport SEXP quasar_cppCalcFeTemplateMatrix(SEXP quasarclPtr_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP feTemplateList_SEXP, SEXP fitParametersList_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type feTemplateList_(feTemplateList_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitParametersList_(fitParametersList_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcFeTemplateMatrix(quasarclPtr_, wavelengthsMatrix_, sizesVector_, feTemplateList_, fitParametersList_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcFeTemplateScaleRates
SEXP cppCalcFeTemplateScaleRates(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP templateFeMatrix_, SEXP sizesVector_, SEXP fitParametersList_);
RcppExport SEXP quasar_cppCalcFeTemplateScaleRates(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP templateFeMatrix_SEXP, SEXP sizesVector_SEXP, SEXP fitParametersList_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type templateFeMatrix_(templateFeMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitParametersList_(fitParametersList_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcFeTemplateScaleRates(quasarclPtr_, spectrumsMatrix_, templateFeMatrix_, sizesVector_, fitParametersList_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcReducedChisqs
SEXP cppCalcReducedChisqs(SEXP quasarclPtr_, SEXP fMatrix_, SEXP yMatrix_, SEXP errorsMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppCalcReducedChisqs(SEXP quasarclPtr_SEXP, SEXP fMatrix_SEXP, SEXP yMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fMatrix_(fMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcReducedChisqs(quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCpuConvolve
SEXP cppCpuConvolve(SEXP quasarclPtr_, SEXP signalVector_, SEXP kernelVector_, SEXP same_);
RcppExport SEXP quasar_cppCpuConvolve(SEXP quasarclPtr_SEXP, SEXP signalVector_SEXP, SEXP kernelVector_SEXP, SEXP same_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type signalVector_(signalVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type kernelVector_(kernelVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type same_(same_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCpuConvolve(quasarclPtr_, signalVector_, kernelVector_, same_));
    return rcpp_result_gen;
END_RCPP
}
// cppReduceFeChisq
SEXP cppReduceFeChisq(SEXP quasarclPtr_, SEXP chisqsVector_, SEXP sizesVector_);
RcppExport SEXP quasar_cppReduceFeChisq(SEXP quasarclPtr_SEXP, SEXP chisqsVector_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type chisqsVector_(chisqsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppReduceFeChisq(quasarclPtr_, chisqsVector_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppFitGaussian
SEXP cppFitGaussian(SEXP quasarclPtr_, SEXP yMatrix_, SEXP xMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppFitGaussian(SEXP quasarclPtr_SEXP, SEXP yMatrix_SEXP, SEXP xMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFitGaussian(quasarclPtr_, yMatrix_, xMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcGaussian
SEXP cppCalcGaussian(SEXP quasarclPtr_, SEXP xMatrix_, SEXP gaussianParamsVector_, SEXP sizesVector_);
RcppExport SEXP quasar_cppCalcGaussian(SEXP quasarclPtr_SEXP, SEXP xMatrix_SEXP, SEXP gaussianParamsVector_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type gaussianParamsVector_(gaussianParamsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcGaussian(quasarclPtr_, xMatrix_, gaussianParamsVector_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcGaussianChisqs
SEXP cppCalcGaussianChisqs(SEXP quasarclPtr_, SEXP xMatrix_, SEXP yMatrix_, SEXP errorsMatrix_, SEXP gaussianParamsVector_, SEXP sizesVector_);
RcppExport SEXP quasar_cppCalcGaussianChisqs(SEXP quasarclPtr_SEXP, SEXP xMatrix_SEXP, SEXP yMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP gaussianParamsVector_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type gaussianParamsVector_(gaussianParamsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcGaussianChisqs(quasarclPtr_, xMatrix_, yMatrix_, errorsMatrix_, gaussianParamsVector_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppCalcGaussianFWHM
SEXP cppCalcGaussianFWHM(SEXP quasarclPtr_, SEXP gaussianParamsVector_);
RcppExport SEXP quasar_cppCalcGaussianFWHM(SEXP quasarclPtr_SEXP, SEXP gaussianParamsVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type gaussianParamsVector_(gaussianParamsVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcGaussianFWHM(quasarclPtr_, gaussianParamsVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppInitialize
SEXP cppInitialize(SEXP sources_);
RcppExport SEXP quasar_cppInitialize(SEXP sources_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sources_(sources_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppInitialize(sources_));
    return rcpp_result_gen;
END_RCPP
}
// cppIsInitialized
SEXP cppIsInitialized(SEXP quasarclPtr_);
RcppExport SEXP quasar_cppIsInitialized(SEXP quasarclPtr_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppIsInitialized(quasarclPtr_));
    return rcpp_result_gen;
END_RCPP
}
// cppSimpleMAVG
SEXP cppSimpleMAVG(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP windowWidth_);
RcppExport SEXP quasar_cppSimpleMAVG(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP windowWidth_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type windowWidth_(windowWidth_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppSimpleMAVG(quasarclPtr_, inputMatrix_, windowWidth_));
    return rcpp_result_gen;
END_RCPP
}
// cppCenteredMAVG
SEXP cppCenteredMAVG(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP colsSizesVector_, SEXP windowWidth_);
RcppExport SEXP quasar_cppCenteredMAVG(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP colsSizesVector_SEXP, SEXP windowWidth_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type colsSizesVector_(colsSizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type windowWidth_(windowWidth_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCenteredMAVG(quasarclPtr_, inputMatrix_, colsSizesVector_, windowWidth_));
    return rcpp_result_gen;
END_RCPP
}
// cppParameterization
SEXP cppParameterization(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP errorsMatrix_, SEXP sizesVector_, SEXP abzVector_, SEXP spectralLinesList_, SEXP continuumWindowsVector_, SEXP ampWavelength_, SEXP feWindowsVector_, SEXP feTemplateList_, SEXP fitParametersList_);
RcppExport SEXP quasar_cppParameterization(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP abzVector_SEXP, SEXP spectralLinesList_SEXP, SEXP continuumWindowsVector_SEXP, SEXP ampWavelength_SEXP, SEXP feWindowsVector_SEXP, SEXP feTemplateList_SEXP, SEXP fitParametersList_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type abzVector_(abzVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectralLinesList_(spectralLinesList_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type continuumWindowsVector_(continuumWindowsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ampWavelength_(ampWavelength_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type feWindowsVector_(feWindowsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type feTemplateList_(feTemplateList_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fitParametersList_(fitParametersList_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppParameterization(quasarclPtr_, spectrumsMatrix_, errorsMatrix_, sizesVector_, abzVector_, spectralLinesList_, continuumWindowsVector_, ampWavelength_, feWindowsVector_, feTemplateList_, fitParametersList_));
    return rcpp_result_gen;
END_RCPP
}
// cppFitElement
SEXP cppFitElement(SEXP quasarclPtr_, SEXP specLinesMatrix_, SEXP continuumsMatrix_, SEXP wavelengthsMatrix_, SEXP errorsMatrix_, SEXP sizesVector_, SEXP element_);
RcppExport SEXP quasar_cppFitElement(SEXP quasarclPtr_SEXP, SEXP specLinesMatrix_SEXP, SEXP continuumsMatrix_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP element_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type specLinesMatrix_(specLinesMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type continuumsMatrix_(continuumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type element_(element_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFitElement(quasarclPtr_, specLinesMatrix_, continuumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, element_));
    return rcpp_result_gen;
END_RCPP
}
// cppGenerateWavelengthsMatrix
SEXP cppGenerateWavelengthsMatrix(SEXP quasarclPtr_, SEXP abzVector_, SEXP spectrumsSize_);
RcppExport SEXP quasar_cppGenerateWavelengthsMatrix(SEXP quasarclPtr_SEXP, SEXP abzVector_SEXP, SEXP spectrumsSize_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type abzVector_(abzVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsSize_(spectrumsSize_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppGenerateWavelengthsMatrix(quasarclPtr_, abzVector_, spectrumsSize_));
    return rcpp_result_gen;
END_RCPP
}
// cppAddSpectrum
SEXP cppAddSpectrum(SEXP quasarclPtr_, SEXP wavelengthsMatrix_, SEXP spectrumsMatrix_, SEXP sizesVector_, SEXP toAddWavelengthsVector_, SEXP toAddSpectrumVector_);
RcppExport SEXP quasar_cppAddSpectrum(SEXP quasarclPtr_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP spectrumsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP toAddWavelengthsVector_SEXP, SEXP toAddSpectrumVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type toAddWavelengthsVector_(toAddWavelengthsVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type toAddSpectrumVector_(toAddSpectrumVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppAddSpectrum(quasarclPtr_, wavelengthsMatrix_, spectrumsMatrix_, sizesVector_, toAddWavelengthsVector_, toAddSpectrumVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppFilterWithWavelengthWindows
SEXP cppFilterWithWavelengthWindows(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP wavelengthsMatrix_, SEXP errorsMatrix_, SEXP sizesVector_, SEXP windowsVector_);
RcppExport SEXP quasar_cppFilterWithWavelengthWindows(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP wavelengthsMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP, SEXP windowsVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type wavelengthsMatrix_(wavelengthsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type windowsVector_(windowsVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFilterWithWavelengthWindows(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppFilterNonpositive
SEXP cppFilterNonpositive(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP aMatrix_, SEXP bMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppFilterNonpositive(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP aMatrix_SEXP, SEXP bMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type aMatrix_(aMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bMatrix_(bMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFilterNonpositive(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppFilterZeros
SEXP cppFilterZeros(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP aMatrix_, SEXP bMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppFilterZeros(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP aMatrix_SEXP, SEXP bMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type aMatrix_(aMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bMatrix_(bMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFilterZeros(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppFilterInfs
SEXP cppFilterInfs(SEXP quasarclPtr_, SEXP spectrumsMatrix_, SEXP aMatrix_, SEXP bMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppFilterInfs(SEXP quasarclPtr_SEXP, SEXP spectrumsMatrix_SEXP, SEXP aMatrix_SEXP, SEXP bMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type spectrumsMatrix_(spectrumsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type aMatrix_(aMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type bMatrix_(bMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppFilterInfs(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppConvolve
SEXP cppConvolve(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP sizesVector_, SEXP filterVector_, SEXP outputMatrix_);
RcppExport SEXP quasar_cppConvolve(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP sizesVector_SEXP, SEXP filterVector_SEXP, SEXP outputMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type filterVector_(filterVector_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type outputMatrix_(outputMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppConvolve(quasarclPtr_, inputMatrix_, sizesVector_, filterVector_, outputMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppCopyIfNotInf
SEXP cppCopyIfNotInf(SEXP quasarclPtr_, SEXP inputMatrix_, SEXP filteredSize_);
RcppExport SEXP quasar_cppCopyIfNotInf(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP, SEXP filteredSize_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type filteredSize_(filteredSize_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCopyIfNotInf(quasarclPtr_, inputMatrix_, filteredSize_));
    return rcpp_result_gen;
END_RCPP
}
// cppCountIfNotInf
SEXP cppCountIfNotInf(SEXP quasarclPtr_, SEXP inputMatrix_);
RcppExport SEXP quasar_cppCountIfNotInf(SEXP quasarclPtr_SEXP, SEXP inputMatrix_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type inputMatrix_(inputMatrix_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppCountIfNotInf(quasarclPtr_, inputMatrix_));
    return rcpp_result_gen;
END_RCPP
}
// cppReglin
SEXP cppReglin(SEXP quasarclPtr_, SEXP xMatrix_, SEXP yMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppReglin(SEXP quasarclPtr_SEXP, SEXP xMatrix_SEXP, SEXP yMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppReglin(quasarclPtr_, xMatrix_, yMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppReglinYax
SEXP cppReglinYax(SEXP quasarclPtr_, SEXP xMatrix_, SEXP yMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppReglinYax(SEXP quasarclPtr_SEXP, SEXP xMatrix_SEXP, SEXP yMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppReglinYax(quasarclPtr_, xMatrix_, yMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppChisq
SEXP cppChisq(SEXP quasarclPtr_, SEXP fMatrix_, SEXP yMatrix_, SEXP errorsMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppChisq(SEXP quasarclPtr_SEXP, SEXP fMatrix_SEXP, SEXP yMatrix_SEXP, SEXP errorsMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fMatrix_(fMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type errorsMatrix_(errorsMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppChisq(quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
// cppTrapz
SEXP cppTrapz(SEXP quasarclPtr_, SEXP yMatrix_, SEXP xMatrix_, SEXP sizesVector_);
RcppExport SEXP quasar_cppTrapz(SEXP quasarclPtr_SEXP, SEXP yMatrix_SEXP, SEXP xMatrix_SEXP, SEXP sizesVector_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type quasarclPtr_(quasarclPtr_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type yMatrix_(yMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type xMatrix_(xMatrix_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type sizesVector_(sizesVector_SEXP);
    rcpp_result_gen = Rcpp::wrap(cppTrapz(quasarclPtr_, yMatrix_, xMatrix_, sizesVector_));
    return rcpp_result_gen;
END_RCPP
}
