# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppLog10 <- function(quasarclPtr_, inputMatrix_) {
    .Call('quasar_cppLog10', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_)
}

cppMinusMatrix <- function(quasarclPtr_, inputMatrix_, subtrahendMatrix_) {
    .Call('quasar_cppMinusMatrix', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, subtrahendMatrix_)
}

cppMinusScalar <- function(quasarclPtr_, inputMatrix_, scalar_) {
    .Call('quasar_cppMinusScalar', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, scalar_)
}

cppMultiplyCol <- function(quasarclPtr_, inputMatrix_, vector_) {
    .Call('quasar_cppMultiplyCol', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, vector_)
}

cppTranspose <- function(quasarclPtr_, inputMatrix_) {
    .Call('quasar_cppTranspose', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_)
}

cppDivide <- function(quasarclPtr_, inputMatrix_, divisorMatrix_) {
    .Call('quasar_cppDivide', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, divisorMatrix_)
}

cppFixReglinResults <- function(quasarclPtr_, cReglinResultsVector_, reglinResultsVector_) {
    .Call('quasar_cppFixReglinResults', PACKAGE = 'quasar', quasarclPtr_, cReglinResultsVector_, reglinResultsVector_)
}

cppCalcCfunDcfun <- function(quasarclPtr_, wavelengthsMatrix_, dcontinuumsMatrix_, continuumsMatrix_, cReglinResultsVector_, reglinResultsVector_) {
    .Call('quasar_cppCalcCfunDcfun', PACKAGE = 'quasar', quasarclPtr_, wavelengthsMatrix_, dcontinuumsMatrix_, continuumsMatrix_, cReglinResultsVector_, reglinResultsVector_)
}

cppCalcCw <- function(quasarclPtr_, wavelengthsMatrix_, continuumsMatrix_, cReglinResultsVector_) {
    .Call('quasar_cppCalcCw', PACKAGE = 'quasar', quasarclPtr_, wavelengthsMatrix_, continuumsMatrix_, cReglinResultsVector_)
}

cppReduceContinuumChisqs <- function(quasarclPtr_, chisqsVector_, sizesVector_) {
    .Call('quasar_cppReduceContinuumChisqs', PACKAGE = 'quasar', quasarclPtr_, chisqsVector_, sizesVector_)
}

cppContinuum <- function(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_, ampWavelength_) {
    .Call('quasar_cppContinuum', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_, ampWavelength_)
}

cppFeFit <- function(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, continuumsMatrix_, sizesVector_, feTemplateList_, windowsVector_, fitParametersList_) {
    .Call('quasar_cppFeFit', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, continuumsMatrix_, sizesVector_, feTemplateList_, windowsVector_, fitParametersList_)
}

cppCalcFeTemplateMatrix <- function(quasarclPtr_, wavelengthsMatrix_, sizesVector_, feTemplateList_, fitParametersList_) {
    .Call('quasar_cppCalcFeTemplateMatrix', PACKAGE = 'quasar', quasarclPtr_, wavelengthsMatrix_, sizesVector_, feTemplateList_, fitParametersList_)
}

cppCalcFeTemplateScaleRates <- function(quasarclPtr_, spectrumsMatrix_, templateFeMatrix_, sizesVector_, fitParametersList_) {
    .Call('quasar_cppCalcFeTemplateScaleRates', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, templateFeMatrix_, sizesVector_, fitParametersList_)
}

cppCalcReducedChisqs <- function(quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_) {
    .Call('quasar_cppCalcReducedChisqs', PACKAGE = 'quasar', quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_)
}

cppCpuConvolve <- function(quasarclPtr_, signalVector_, kernelVector_, same_) {
    .Call('quasar_cppCpuConvolve', PACKAGE = 'quasar', quasarclPtr_, signalVector_, kernelVector_, same_)
}

cppReduceFeChisq <- function(quasarclPtr_, chisqsVector_, sizesVector_) {
    .Call('quasar_cppReduceFeChisq', PACKAGE = 'quasar', quasarclPtr_, chisqsVector_, sizesVector_)
}

cppFitGaussian <- function(quasarclPtr_, yMatrix_, xMatrix_, sizesVector_) {
    .Call('quasar_cppFitGaussian', PACKAGE = 'quasar', quasarclPtr_, yMatrix_, xMatrix_, sizesVector_)
}

cppCalcGaussian <- function(quasarclPtr_, xMatrix_, gaussianParamsVector_, sizesVector_) {
    .Call('quasar_cppCalcGaussian', PACKAGE = 'quasar', quasarclPtr_, xMatrix_, gaussianParamsVector_, sizesVector_)
}

cppCalcGaussianChisqs <- function(quasarclPtr_, xMatrix_, yMatrix_, errorsMatrix_, gaussianParamsVector_, sizesVector_) {
    .Call('quasar_cppCalcGaussianChisqs', PACKAGE = 'quasar', quasarclPtr_, xMatrix_, yMatrix_, errorsMatrix_, gaussianParamsVector_, sizesVector_)
}

cppCalcGaussianFWHM <- function(quasarclPtr_, gaussianParamsVector_) {
    .Call('quasar_cppCalcGaussianFWHM', PACKAGE = 'quasar', quasarclPtr_, gaussianParamsVector_)
}

cppInitialize <- function(sources_) {
    .Call('quasar_cppInitialize', PACKAGE = 'quasar', sources_)
}

cppIsInitialized <- function(quasarclPtr_) {
    .Call('quasar_cppIsInitialized', PACKAGE = 'quasar', quasarclPtr_)
}

cppSimpleMAVG <- function(quasarclPtr_, inputMatrix_, windowWidth_) {
    .Call('quasar_cppSimpleMAVG', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, windowWidth_)
}

cppCenteredMAVG <- function(quasarclPtr_, inputMatrix_, colsSizesVector_, windowWidth_) {
    .Call('quasar_cppCenteredMAVG', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, colsSizesVector_, windowWidth_)
}

cppParameterization <- function(quasarclPtr_, spectrumsMatrix_, errorsMatrix_, sizesVector_, abzVector_, spectralLinesList_, continuumWindowsVector_, ampWavelength_, feWindowsVector_, feTemplateList_, fitParametersList_) {
    .Call('quasar_cppParameterization', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, errorsMatrix_, sizesVector_, abzVector_, spectralLinesList_, continuumWindowsVector_, ampWavelength_, feWindowsVector_, feTemplateList_, fitParametersList_)
}

cppFitElement <- function(quasarclPtr_, specLinesMatrix_, continuumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, element_) {
    .Call('quasar_cppFitElement', PACKAGE = 'quasar', quasarclPtr_, specLinesMatrix_, continuumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, element_)
}

cppGenerateWavelengthsMatrix <- function(quasarclPtr_, abzVector_, spectrumsSize_) {
    .Call('quasar_cppGenerateWavelengthsMatrix', PACKAGE = 'quasar', quasarclPtr_, abzVector_, spectrumsSize_)
}

cppAddSpectrum <- function(quasarclPtr_, wavelengthsMatrix_, spectrumsMatrix_, sizesVector_, toAddWavelengthsVector_, toAddSpectrumVector_) {
    .Call('quasar_cppAddSpectrum', PACKAGE = 'quasar', quasarclPtr_, wavelengthsMatrix_, spectrumsMatrix_, sizesVector_, toAddWavelengthsVector_, toAddSpectrumVector_)
}

cppFilterWithWavelengthWindows <- function(quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_) {
    .Call('quasar_cppFilterWithWavelengthWindows', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, wavelengthsMatrix_, errorsMatrix_, sizesVector_, windowsVector_)
}

cppFilterNonpositive <- function(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_) {
    .Call('quasar_cppFilterNonpositive', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_)
}

cppFilterZeros <- function(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_) {
    .Call('quasar_cppFilterZeros', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_)
}

cppFilterInfs <- function(quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_) {
    .Call('quasar_cppFilterInfs', PACKAGE = 'quasar', quasarclPtr_, spectrumsMatrix_, aMatrix_, bMatrix_, sizesVector_)
}

cppConvolve <- function(quasarclPtr_, inputMatrix_, sizesVector_, filterVector_, outputMatrix_) {
    .Call('quasar_cppConvolve', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, sizesVector_, filterVector_, outputMatrix_)
}

cppCopyIfNotInf <- function(quasarclPtr_, inputMatrix_, filteredSize_) {
    .Call('quasar_cppCopyIfNotInf', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_, filteredSize_)
}

cppCountIfNotInf <- function(quasarclPtr_, inputMatrix_) {
    .Call('quasar_cppCountIfNotInf', PACKAGE = 'quasar', quasarclPtr_, inputMatrix_)
}

cppReglin <- function(quasarclPtr_, xMatrix_, yMatrix_, sizesVector_) {
    .Call('quasar_cppReglin', PACKAGE = 'quasar', quasarclPtr_, xMatrix_, yMatrix_, sizesVector_)
}

cppReglinYax <- function(quasarclPtr_, xMatrix_, yMatrix_, sizesVector_) {
    .Call('quasar_cppReglinYax', PACKAGE = 'quasar', quasarclPtr_, xMatrix_, yMatrix_, sizesVector_)
}

cppChisq <- function(quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_) {
    .Call('quasar_cppChisq', PACKAGE = 'quasar', quasarclPtr_, fMatrix_, yMatrix_, errorsMatrix_, sizesVector_)
}

cppTrapz <- function(quasarclPtr_, yMatrix_, xMatrix_, sizesVector_) {
    .Call('quasar_cppTrapz', PACKAGE = 'quasar', quasarclPtr_, yMatrix_, xMatrix_, sizesVector_)
}

